<<<<<<< HEAD
# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
=======
# config/services.yaml
parameters:
    mailer_from: 'elhantatiichraq16@gmail.com'

services:
    # Configuration par défaut pour les services
    _defaults:
        autowire: true      # Injection automatique des dépendances
        autoconfigure: true # Enregistre automatiquement les services comme commandes, subscribers, etc.

    # Bind par défaut si un constructeur demande $session (optionnel)
    # bind:
    #     $session: '@session' 

    # Rendre toutes les classes dans src/ disponibles comme services
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # Déclaration des controllers comme services
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        autowire: true

    # Services spécifiques
    App\Service\Ventes\ValidationForm:
        arguments:
            $validationService: '@App\Service\Ventes\ValidationService'
            $globalService: '@App\Service\GlobalService'
            $requestStack: '@request_stack' # <- Correction ici

    App\Service\Ventes\ValidationService: ~
    App\Service\GlobalService: ~
>>>>>>> e7a4decc1af809cb329bcab97a5b7e0b1153b252
